### ISSUE TITLE
KOLIBRI_HOME

### ISSUE THREAD

**Issue by Odia1** [learningequality/kolibri-installer-debian#10]

**Comment by indirectlylit** [comment]
Hi @Odia1 - could you please provide:

* observed behavior
* expected behavior
* user-facing consequences
* errors and logs
* steps to reproduce
* Kolibri version and operating system

thanks!

**Comment by Odia1** [comment]
1. I fail to install kolibri on both Mint 18.2 and 18.3.  It fails as such
when I do "apt-get install kolibri":

Setting up kolibri (0.6.0-0ubuntu1) ...
/etc/kolibri/conf.d/*.conf
kolibri:x:122:65534::/var/kolibri:/bin/bash
Failed to execute operation: No such file or directory
Traceback (last called is first):
     kolibri_configure() in /var/lib/dpkg/info/kolibri.postinst:1
     main() in /var/lib/dpkg/info/kolibri.postinst:175
dpkg: error processing package kolibri (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 kolibri
E: Sub-process /usr/bin/dpkg returned an error code (1)



2. Then I faked by putting a dummy.conf in directory
/etc/kolibri/conf.d/*.conf and it made a couple more steps and failed:

Setting up kolibri (0.6.0-0ubuntu1) ...
/etc/kolibri/conf.d/dummy.conf
kolibri:x:122:65534::/var/kolibri:/bin/bash
Failed to execute operation: No such file or directory
Traceback (last called is first):
     kolibri_configure() in /var/lib/dpkg/info/kolibri.postinst:1
     main() in /var/lib/dpkg/info/kolibri.postinst:175
dpkg: error processing package kolibri (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 kolibri
E: Sub-process /usr/bin/dpkg returned an error code (1)


3. ALso, I don't know that uninstall cleanly removes kolibri.


thanks and please get back to me on this.

**Comment by benjaoming** [comment]
Hi @Odia1 

Thanks for reporting this! Have seen a similar report where the user environment from the wrong user got passed to the system service script. I will investigate and report back!

**Comment by benjaoming** [comment]
Hi @Odia1 

You will probably not experience the reported issue in 0.7.2: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri/

I'll close this, but I did also manage to find problems that are similar to what you report. They have been worked out for 0.7 and will be finally addressed in 0.8 where specifying `KOLIBRI_HOME` in  a settings for the system service will also be supported.

Thanks for reporting!
