### ISSUE TITLE
Add Python 3.6 support

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-debian#29]
While I'm not convinced that it works, I think we should enable it and see what comes up.

**Comment by benjaoming** [comment]
Example from a user:

![image](https://user-images.githubusercontent.com/374612/38371903-e2b281ba-38ed-11e8-8b1f-9a17d284d58b.png)

**Comment by indirectlylit** [comment]
>  I'm not convinced that it works

What are your concerns?

**Comment by lyw07** [comment]
Will look into this today.

@indirectlylit If I remember correctly, I think @benjaoming 's concern is related to this issue: https://github.com/learningequality/iceqube/issues/29

**Comment by benjaoming** [comment]
@lyw07 let's release it, we can only become wiser :)

**Comment by radinamatic** [comment]
@lyw07 Let me know when it is ready on Launchpad to grab for testing! 👍

**Comment by lyw07** [comment]
@benjaoming @radinamatic Thank you! Will create a 0.9.0-0ubuntu3 build later today on `kolibri-proposed` for testing

**Comment by lyw07** [comment]
Hi @neyder ,

Do you mind sharing the error you got when installing `0.9.0-0ubuntu2` without using the --ignore-dependences option? Thank you so much!

**Comment by lyw07** [comment]
Builded `0.9.0-0ubuntu3` for Python 3.6 support. Thanks @radinamatic for testing! It's now on `kolibri` PPA.

**Comment by benjaoming** [comment]
This is fixed and published since @lyw07 's update!
