### ISSUE TITLE
allow kolibri process to access mounted drives

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-debian#40]
Original thread here: https://learningequality.slack.com/archives/CB37UM23A/p1528926956000142

1. The **primary issue** is that the `kolibri` user does not have permission to access drives in some circumstances. This has led to legitimate drives being filtered out in [some cases](https://github.com/learningequality/kolibri/issues/3068).
2. A **secondary issue** is that when people run Kolibri commands as a regular user and the main Kolibri service is owned by the `kolibri` user, `KOLIBRI_HOME` has two different values. This [leads to confusion](https://github.com/learningequality/kolibri/issues/3274). We can probably address this in a [separate issue](https://github.com/learningequality/kolibri-installer-debian/issues/41), but may have implications for the UX of (1).

Some ideas discussed:

* give the `kolibri` user access to drives by adding it to the `plugdev` group
  * might help for a headless setup?
  * does not help in the case where a normal user is logged in, because OS will mount drive in a location only accessible to that user
* have kolibri run as a normal user
  * might require user to manually log in to start server? Unless when the server boots it automatically logs in the user?
  * this might be the same as installing without a system service?
* instruct users to copy content to a location that can be accessed by the kolibri process
  * doesn't help with headless case
  * extra step in the UX
* have two processes running owned by different users
  * somewhat complex and requires changes to app code
* add `kolibri` user to sudo and give narrow permission to use `mount`. add a udev rule to auto-mount drives under a `kolibri`-user accessible location

**Comment by radinamatic** [comment]
> give the `kolibri` user access to drives by adding it to the `plugdev` group

Tried this during the integration testing of the upgrade on Ubuntu 16.04, and it did not solve the issue. Kolibri was unable to access the attached USB drive after running the command and rebooting the system.

**Comment by jredrejo** [comment]
I think we should try the latest idea as it's the one that could be implemented fast enough to solve the problem for our next release. I'd like to know  @benjaoming  opinion on this, and in case he likes it, I can lend a hand /do it if needed.

**Comment by benjaoming** [comment]
I'm writing a proposal for this, please allow me some time.

Thanks for the input @indirectlylit

**Comment by jredrejo** [comment]
@benjaoming if we opt to use the third option, it's going to require changes in the backend too, to use `sudo mount` to mount the usb folder.
If you have other ideas I think it would be good to discuss it before the week ends, to be sure we can solve it just using the packaging.

**Comment by indirectlylit** [comment]
>> find a work-around for this next week

> I thought about this quite a lot, and I think this is entirely about the .deb. So a Kolibri release can happen with a later .deb build fixing the issue.

@benjaoming sorry no, we still need to get it fixed this week. The comms team is planning on doing a small PR splash, and so we're expecting a bump in the number of new installations and users.

**Comment by indirectlylit** [comment]
(this can be a first pass or workaround)

**Comment by indirectlylit** [comment]
let's plan on having a breakout discussion after the dev meeting to decide on a course of action

**Comment by indirectlylit** [comment]
Outcomes from meeting - attempt for this week, next couple days preferably:

* make new default behavior to use normal user rather than creating a new user
* existing installations will continue to use the `kolibri` user after upgrade
  * (these users will not be able to access mounted drives. We can advice separately on how to migrate)

Separately, we'll create application logic addressing the secondary issue:  https://github.com/learningequality/kolibri/issues/3881

**Comment by benjaoming** [comment]
This is solved in 0.10.0 in the sense that we are now encouraging the desktop user account as the default account.

We should open up new issues if we decide to work on a more refined system user account with USB permissions and such.
