### ISSUE TITLE
Update KOLIBRI_HTTP_PORT used in system service

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-debian#47]
It's legacy, must change to `KOLIBRI_LISTEN_PORT`

Furthermore, consolidate the list of `export` statements here: https://github.com/learningequality/kolibri-installer-debian/blob/1876acc0067f80093cbd03c9bc5293ca4f93c8cf/debian/startup/kolibri.default#L44 and give further guidance in case other environment vars are set, which should be picked up by `options.ini` defaults.

CC: @jamalex

**Comment by indirectlylit** [comment]
cool
