### ISSUE TITLE
Discussion: debconf philosophy

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-debian#5]
I'm proposing to not use debconf at all.

Observe the following layer of priorities for assigning configuration values (from lowest to highest):

1. Default values of `kolibri` (from source distribution, for instance default port is 8080)
1. Default configuration values for the system startup script, located in `/etc/default/kolibri`, this file is maintained by the package and should not be changed by the user
1. Additional configuration files from debian package (provided by other remixed packages such as `kolibri-nginx`) in `/etc/kolibri/conf.d/*`
1. User maintained config files in `/etc/kolibri/kolibri.conf` that should not need updates or cause breakage when modified and package is updated

If we had configuration values from debconf, we would have to inject them somewhere. KA Lite created special files with these values, and those files weren't changed by the user, but would get overwritten every time KA Lite updates, which in essence meant that `kalite user`, `kalite port`, and `kalite homedir` could only be managed through the debconf.

I also observed that debconf isn't widely used for deployments. Simply because people aren't familiar with it, and its API is akward and badly documented.

What made KA Lite packaging a huge mess was all the debconf values that had to be matched up against some state of the system and whether they had changed or not during upgrades.

**Comment by indirectlylit** [comment]
that sounds totally reasonable to me.

cc @jamalex and @rtibbles this relates to the ongoing question of "where and how config is stored" for various values of "config".

**Comment by benjaoming** [comment]
You can see the changes in #6, but for clarity, the layout is like this:

### /etc/default/kolibri

```
# 1. Set the default values

KOLIBRI_USER="kolibri"
KOLIBRI_HOME="~/.kolibri"
KOLIBRI_LISTEN_PORT="8080"
KOLIBRI_COMMAND="kolibri"
DJANGO_SETTINGS_MODULE="kolibri.deployment.default.settings.base"

# 2. Load conf.d directory

if [ -d /etc/kolibri/conf.d ]
then
  for f in /etc/kolibri/conf.d/*.conf
  do
    . "$f"
  done
fi

# 3. Load user configuration

if [ -e /etc/kolibri/daemon.conf ]
then
  . /etc/kolibri/daemon.conf
fi
```

### /etc/kolibri/daemon.conf

Default placeholder contents:

```
# Define kolibri environment settings here
#
# This is a Debian specific file
#
# Example environment vars to set (shell syntax)
#
# KOLIBRI_USER="kolibri"
# KOLIBRI_HOME="~/.kolibri"
# KOLIBRI_LISTEN_PORT="8080"
# KOLIBRI_COMMAND="kolibri"
# DJANGO_SETTINGS_MODULE="kolibri.deployment.default.settings.base"

```

### /etc/kolibri/conf.d

Any file here will be added to configuration and executed in the system service. Useful for other packages to add special configurations. Not clear how it will be used yet, and might be adapted.

### /etc/init.d/kolibri

```
#!/bin/sh

# Author: Foundation for Learning Equality
#
# /etc/init.d/kolibri

### BEGIN INIT INFO
# Provides:          kolibri
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: kolibri daemon, an offline education platform
### END INIT INFO

set -e

if !(whoami | grep "root" -q)
then
        echo "You need to be root"
        exit 1
fi

PATH=/bin:/usr/bin:/sbin:/usr/sbin

. /lib/lsb/init-functions

. /etc/default/kolibri

case "$1" in
  start)
    # run ka-lite as another user, the one who generated this file
    su $KOLIBRI_USER -l -p -s /bin/sh -c "$KOLIBRI_COMMAND start"
    ;;
  stop)
    su $KOLIBRI_USER -l -p -s /bin/sh -c "$KOLIBRI_COMMAND stop"
    ;;
  restart)
    su $KOLIBRI_USER -l -p -s /bin/sh -c "$KOLIBRI_COMMAND restart"
    ;;
  status)
    su $KOLIBRI_USER -l -p -s /bin/sh -c "$KOLIBRI_COMMAND status"
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/kolibri {start|stop|restart|status}"
    exit 1
esac

```

**Comment by benjaoming** [comment]
Okay, I've actually added 3 debconf template entries... for the user to choose whether to run Kolibri at startup or not. Based on the user's choice some instructions are displayed. This is the same as KA Lite @radinamatic -- but with a few adjustments.

```
Template: kolibri/init
Type: boolean
Default: true
Description: Do you wish to run Kolibri on start-up?
 This will automatically call the system service to start
 Kolibri when your system boots.

Template: kolibri/init-instructions
Type: note
Description: The Kolibri system service
 You have chosen to run Kolibri as a system
 service and it has been started automatically. You can
 start/stop/restart Kolibri with the following command
 .
   sudo service kolibri [start, stop, restart]

Template: kolibri/manual-instructions
Type: note
Description: Running Kolibri manually:
 You have chosen not to run Kolibri as a system
 service and that means you should run it manually.
 Starting Kolibri with your current user account:
 .
   kolibri start
 .
 Starting Kolibri as a system-wide service:
 .
   sudo service kolibri start
 .
 Start Kolibri when the system boots:
 .
   sudo systemctl enable kolibri

```
