### ISSUE TITLE
System service owner needs a default group

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-debian#60]
There are indications that the WAL (write-ahead log) in Sqlite3 has issues if the owner of the `kolibri` process isn't assigned a default group. This is known to cause lots of `Database I/O Error` under medium loads, causing Kolibri to crash.

The behavior wasn't seen until 0.11.

Will issue a fix for 0.11 before 0.12 arrives.

Am intending to change targets: `configure` (for creating new users) and in `postinst` for checking existing users if it's an upgrade. I would probably just throw a log message like "Chosen kolibri system user 'x' does not have a primary group and one will be assigned...".

For existing configurations, we will try to create a default group for user 'x' named 'x' as well, but suffix it 'x_y' in case 'x' already exists.

* [x] Set a primary group for new system users
* [x] Set a primary group for existing system users
* [ ] Existing `~/.kolibri` directories and contents aren't reassigned to the new group.

**Comment by indirectlylit** [comment]
> There are indications that the WAL (write-ahead log) in Sqlite3 has issues if the owner of the `kolibri` process isn't assigned a default group.

have we been able to reproduce this? why did it only start happening in 0.11?

**Comment by benjaoming** [comment]
> have we been able to reproduce this? why did it only start happening in 0.11?

Unfortunately, it could still be coincidence with some added context that my provoke more easily in 0.11. We are still waiting for a confirmation from the reporter.

The reason this doesn't show up often is because Kolibri service is set to run on the default desktop user's account (for USB device access) which has a primary group.

But there's no reason to NOT do this.. and having this doubt can help us narrow down the cause.

**Comment by benjaoming** [comment]
It seems confirmed that this does NOT fix the "I/O Error".

I'm gonna merge this anyways, as it's been released and doesn't cause harm.

**Comment by benjaoming** [comment]
There's one item missing in this fix:

Existing `~/.kolibri` directories and contents aren't reassigned to the new group: We should consider doing this to ensure that upgrades are consistent.

**Comment by benjaoming** [comment]
The reporter had reported a different database error, so actually the problem does seem to be fixed. This makes it all the more relevant to conclude this work with the final part:

> 
Existing `~/.kolibri` directories and contents aren't reassigned to the new group: We should consider doing this to ensure that upgrades are consistent.
