### ISSUE TITLE
Need option for a --debug flag

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-debian#88]
Invoking `kolibri` from the system service currently doesn't have any good options for adding a `--debug` flag.

This could be understood as an upstream issue: Kolibri does not support DEBUG=True from environment or similar.

It could also be understood as a more generic issue: Our `/etc/default/kolibri` or `/etc/kolibri/daemon.conf` does not add a settings variable, for instance `KOLIBRI_START_ARGS` etc.

**Comment by benjaoming** [comment]
We could add some commented out example configuration in `/etc/kolibri/daemon.conf`

Slightly related: #85

**Comment by jredrejo** [comment]
hi @benjaoming could you ellaborate a bit the purpose of the `--debug` flag? I don't see it having all the logs we have in the app, and I can't imagine a normal user debugging the app.

**Comment by benjaoming** [comment]
@jredrejo I needed to be able to instruct a user of the .deb package to debug, but I did't find the current way simple enough: https://community.learningequality.org/t/delay-with-the-coach-interface-on-kolibri/1421/6?u=benjamin

It can be argued that a deeper lying logging issue is the reason why I needed to ask for `--debug`, but I think we could encounter a need for it in the future -- or indeed another CLI arg for `kolibri start`.

**Comment by jredrejo** [comment]
Sorry but I don't see it. If you want to tell an user how to debug, the user should know Python, thus you can send him to https://kolibri-dev.readthedocs.io/
If the user does not know Python I don't know how he could debug. 
If you want to debug the daemon behaviour, systemd already has debug information :
`systemctl status kolibri` or, for more verbose information:
`SYSTEMD_LOG_LEVEL=debug journalctl -u kolibri`
provide all the needed information.

what else do you want to get with a `--debug` flag?

**Comment by benjaoming** [comment]
I'm not asking the user to debug, I'm asking them to use the flag and send me debug logs.

**Comment by benjaoming** [comment]
https://github.com/learningequality/kolibri/pull/6619 will introduce `KOLIBRI_DEBUG` which we can add as an example option to `/etc/kolibri/daemon.conf` and `/etc/kolibri/README`.

**Comment by jredrejo** [comment]
@benjaoming https://github.com/learningequality/kolibri/pull/6619  is already merged, can we close this issue now?

**Comment by benjaoming** [comment]
I wanted to add it as an example, let me quickly do a PR for that, it's just commented out code...
